import { Doctor, ScheduleSlot } from './types';

// Raw data corrected and provided by the user
const RAW_DATA = `EJECUTIVO,NOMBRE,ESPECIALIDAD,SUB ESPECIALIDAD,DIRECCION,HOSPITAL,CONSULTORIO,PISO,TELEFONO,CORREO ELECTRONICO,CEDULA PROFESIONAL,FECHA DE NACIMIENTO,ASEGURADORA,CATEGORIA,ESTILO SOCIAL,SEGMENTO ACTITUDINAL,HORA DE ATENCIÓN,OBSERVACIONES
ORALIA,José Gustavo Martínez Lugo,Ginecología y Obstetricia,,Calzada de Guadalupe,,,,,,,,,,,,,
ORALIA,Denys Elizabeth Delgado Amador,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ORALIA,Francisco Javier Guerrero Carreño,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ORALIA,Javier Hernández Torres,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Adia Carrillo Pacheco,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Adrián García Álvarez,Ginecología y Obstetricia,,Avenida Prados de Cedro S/N Medical Tower,,,,,,,,,,,,,
LUIS,Adrián González Zuria,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Adriana Esquivel Cervantes,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Adriana Galván Luna,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Adriana López Franco,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
LUIS,Adriana Mercedes Acuña Euan,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Aída Simbrón,Ginecología y Obstetricia,,"Homero 1425, Polanco",,,,,,,,,,,,,
ORALIA,Aidé Yukieskany González Vega,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
TALINA,Alan de Jesús Martínez Salas,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Alba Jasso Gerardo Andrés,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ORALIA,Alba Myriam García Rodríguez,Ginecología y Obstetricia,Biología de la Reproducción,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
ANGEL,Alba Nuri Zúñiga Rodríguez,Ginecología y Obstetricia,Biología de la Reproducción,Torre Durango 64,,,,,,,,,,,,,
ANGEL,Alberto Eduardo Jacobo Basto,Ginecología y Obstetricia,Biología de la Reproducción,Torre Durango 49,,,,,,,,,,,,,
ANGEL,Alberto Trejo Fausto,Urología,,"Tuxpan 9, piso 6, cons 612, Roma Sur",,,,,,,,,,,,,
ANGEL,Alberto Vielma Valdés,Ginecología y Obstetricia,Biología de la Reproducción,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Aldo Isaac Meneses Ríos,Ginecología y Obstetricia,Biología de la Reproducción,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,Alejandra Bravo Figueroa,Ginecología y Obstetricia,Biología de la Reproducción,MAC La Viga,,,,,,,,,,,,,
LUIS,Alejandra García,Ginecología y Obstetricia,Biología de la Reproducción,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Alejandra Gómez Martínez,Ginecología y Obstetricia,Biología de la Reproducción,MAC La Viga,,,,,,,,,,,,,
LUIS,Alejandra López Chávez,Ginecología y Obstetricia,Biología de la Reproducción,HMG,,,,,,,,,,,,,
TALINA,Alejandra Marcela Santiago Aguirre,Ginecología y Obstetricia,Biología de la Reproducción,Hospital Ángeles Pedregal (Nueva Torre Clínica Piso 9 Consultorio 990),,,,,,,,,,,,,
ANGEL,Alejandra Martínez Goldaracena,Ginecología y Obstetricia,Biología de la Reproducción,Frontera 74 Roma Norte,,,,,,,,,,,,,
TALINA,Alejandra Martínez Schulte,Ginecología y Obstetricia,Biología de la Reproducción,"Hospital Ángeles Pedregal, Torre Ángeles, piso 8, consultorio 825",,,,,,,,,,,,,
ORALIA,Alejandra Ortega Gutiérrez,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Alejandra Robledo Torres,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Alejandra Vega León,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
TALINA,Alejandro Ortiz de la Peña y Carranza,Ginecología y Obstetricia,,Camino a Santa Teresa,,,,,,,,,,,,,
TALINA,Alejandro Alias Melgar,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Alejandro Cumming Martínez Báez,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Alejandro Escobedo Díaz,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
ORALIA,Alejandro Labastida,Ginecología y Obstetricia,,"Alexander Von Humboldt 88, Lomas Verdes 3ra Secc, 53120 Naucalpan de Juárez, Méx",,,,,,,,,,,,,
ORALIA,Alejandro López Monter,Ginecología y Obstetricia,,"Av. Montevideo 303, Lindavista",,,,,,,,,,,,,
LUIS,Alejandro Noyola Guadarrama,Urología,,Av. División del Norte,,,,,,,,,,,,,
LUIS,Alejandro Rendón Molina,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
TALINA,Alejandro Sierra Torres,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Alfonso Armesto Santos,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
TALINA,Alfonso Armesto Santos,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Alfonso de Jesús Valle Escalante,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Alfonso Murillo Uribe,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Alfonso Sustaita Ballinas,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Alfredo González Cortés,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Alfredo Saad Ganem,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ANGEL,Alicia Guzmán Guzmán,Ginecología y Obstetricia,,Gobernador Gregorio V. 29 Miguel Hidalgo,,,,,,,,,,,,,
ORALIA,Aline Alejandra Bermúdez,Ginecología y Obstetricia,,Av. Dr. Gustavo Baz 309-TR A1,,,,,,,,,,,,,
ANGEL,Alma Delia Ávila Arreaga,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
TALINA,Alma Edith García Franco,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Alma Esther Navarro Sánchez,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Alma Itzel Cruz Picazo,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Alondra Acala Ochoa,Ginecología y Obstetricia,,"Alexander Von Humboldt 88, Lomas Verdes 3ra Secc, 53120 Naucalpan de Juárez, Méx",,,,,,,,,,,,,
LUIS,Álvaro Eduardo Peña Jiménez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Ana Carina Vázquez Martínez,Ginecología y Obstetricia,,"Av. Montevideo 303, Lindavista",,,,,,,,,,,,,
ANGEL,Ana Cedillo Sotelo Rubio,Ginecología y Obstetricia,,Torre Tuxpan 6,,,,,,,,,,,,,
ORALIA,Ana Cristina Arteaga Gómez,Ginecología y Obstetricia,Ginecología Oncológica,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
ORALIA,Ana Cristina Salazar Melchor,Ginecología y Obstetricia,,"Temístocles 210, Polanco IV Sección",,,,,,,,,,,,,
LUIS,Ana Gabriela Carrillo Rodríguez,Ginecología y Obstetricia,,Consultorio privado,,,,,,,,,,,,,
TALINA,Ana Karen Gutiérrez Aguilar,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Ana Karen Luna Reséndiz,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ANGEL,Ana Laura Bello Madrid,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
ANGEL,Ana María Rodríguez Rojas,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ANGEL,Ana María Velasco Guzmán,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Ana Mireya Núñez García,Ginecología y Obstetricia,,Hospital MAC Cuemanco,,,,,,,,,,,,,
TALINA,Ana Paola Sánchez Serrano,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Ana Victoria Flores Hernández,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Ana Yemci Franco Uribe,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,Andrea Paulina Salinas Quiroz,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Andreas Madariaga,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
ORALIA,Andrés Alejandro Rosero Flores,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Andrés Flores,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
TALINA,Andrés Gudiño Chávez,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Andrés Iván Morales Cervantes,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Andrés Vicente Vela Vizuet,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
TALINA,Andrey Ramírez Ramírez,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Ángel Allan Díaz Quevedo,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Ángel Antonio Licona Vázquez,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
TALINA,Ángel Antonio Licona Vázquez,Ginecología y Obstetricia,Uroginecología,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,Ángel Elizalde Méndez,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
TALINA,Ángel Lemus Huerta,Ginecología y Obstetricia,,Camino a Santa Teresa,,,,,,,,,,,,,
ORALIA,Ángel Millán Juárez,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ANGEL,Ángeles Juárez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Angélica Figueras López,Ginecología y Obstetricia,,"Av. Montevideo 303, Lindavista",,,,,,,,,,,,,
ANGEL,Antonio Alcázar Alarcón,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ORALIA,Antonio Carvajal Gómez,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ANGEL,Antonio Guzmán A.,Ginecología y Obstetricia,,Tepic 139,,,,,,,,,,,,,
LUIS,Araceli Montaño Román,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ANGEL,Aracely Matías Olvera,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ANGEL,Arcadio Morales,Ginecología y Obstetricia,,Eje 3 Sur 218 Roma Sur,,,,,,,,,,,,,
TALINA,Arely Peña García,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Ariadna Elizabeth Ortega Díaz,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Ariadna Sánchez Mendoza,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Armado Ayala Macín,Ginecología y Obstetricia,,Paseo Alexander Von Humboldt 88,,,,,,,,,,,,,
LUIS,Armando Avilez Bacre,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Armando Ramírez Carrasco,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Armando Ruiz Valdez,Ginecología y Obstetricia,,Tuxpan 39,,,,,,,,,,,,,
LUIS,Arnulfo Cañas Trujillo,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ORALIA,Arturo Jorge Esparza,Ginecología y Obstetricia,,Av. Lomas Verdes,,,,,,,,,,,,,
TALINA,Arturo Mendoza Valdés,Urología,,Puente de Piedra,,,,,,,,,,,,,
ORALIA,Asael Flores García,Ginecología y Obstetricia,,Montiel,,,,,,,,,,,,,
LUIS,Auria Avendaño Pérez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Aurora Gómez Romero,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ORALIA,Baños Hernández Karina Lizbeth,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Beatriz Monroy Castillo,Ginecología y Obstetricia,,Tepic 139,,,,,,,,,,,,,
ORALIA,Bedia Sánchez Luis Miguel,Ginecología y Obstetricia,Biología de la Reproducción,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ORALIA,Belem Carolina de Alba González,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
LUIS,Benjamín Orozco Zúñiga,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Berenice Círigo Hernández,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Berenice Flores Maldonado,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Bernardett Orizaba Chávez,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Bernardo Fernández Salazar,Ginecología y Obstetricia,,Torre Durango 49,,,,,,,,,,,,,
ANGEL,Bertha Cecilia de Ávila,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
ORALIA,Bertha Piña Ángeles,Ginecología y Obstetricia,,Enrique Sada Muguerza 17,,,,,,,,,,,,,
LUIS,Bibiana Aldanoli Arredondo Rodríguez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Blanca Rodríguez Grijalva,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
TALINA,Braulio Gerardo Quesada Reyna,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Brenda Sánchez Ramírez,Ginecología y Obstetricia,Biología de la Reproducción,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
ORALIA,Campos Reyes Brenda,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Carla América Suárez Juárez,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
TALINA,Carlos Alberto González Espinosa,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Carlos Alberto Servín Hernández,Ginecología y Obstetricia,,Tehuantepec,,,,,,,,,,,,,
LUIS,Carlos Andrés Sánchez Arreola,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
TALINA,Carlos Antonio Godínez Nava,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Carlos Benjamín Castañeda Valdivia,Ginecología y Obstetricia,,Querétaro 58 Roma Norte,,,,,,,,,,,,,
ANGEL,Carlos Enrique Galicia García,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Carlos Enrique Pérez Serna,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Carlos Enrique Soto Aburto,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Carlos José Molina Pérez,Ginecología y Obstetricia,,IMSS 4,,,,,,,,,,,,,
TALINA,Carlos Martínez Arroyo,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Carlos Zapico Ortiz,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
LUIS,Carmen Lizeth Olmos Mejía,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Carmen Rosa Mejía Villarroel,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Carolina Castillo Giacoman,Ginecología y Obstetricia,,Torre Durango 33,,,,,,,,,,,,,
ANGEL,Carolina Contreras,Ginecología y Obstetricia,,Tepic 113,,,,,,,,,,,,,
ANGEL,Carolina Contreras,Ginecología y Obstetricia,,Torre Tepic 113,,,,,,,,,,,,,
ANGEL,Carolina Garmendia Gallardo,Ginecología y Obstetricia,,Tuxpan 54,,,,,,,,,,,,,
ANGEL,Carolina Navarro Venegas,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Castañeda Arreola Gerardo,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Catalina Barrón Álvarez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Cecilia Camacho Ríos,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Cecilio Rodríguez Ayala,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
ANGEL,César Abimael C. Alcázar,Ginecología y Obstetricia,,Tuxpan 54,,,,,,,,,,,,,
ANGEL,César Jair López de la Rosa,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
LUIS,César Rodríguez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,César Santiago,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ANGEL,César Yair López de la Rosa,Ginecología y Obstetricia,,Querétaro,,,,,,,,,,,,,
TALINA,Christian Isaac Villeda Sandoval,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Christian Rodríguez Castillo,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
TALINA,Christian Ronald Choque Hidalgo,Ginecología y Obstetricia,,Hospital Ángeles del Pedregal Torre Clínica Ángeles Con 990,,,,,,,,,,,,,
ORALIA,Cinthia Lizeth Juárez Leal,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Cinthia Yuridia Maciel Valentín,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
LUIS,Cinthya Verver Moreno,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Cintia María Sepúlveda Rivera,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Cintia Mejía García,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Claudia Elena,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
ANGEL,Claudia Morelos Mellado,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
ANGEL,Claudia Ochoa Navarrete,Ginecología y Obstetricia,,Torre Querétaro,,,,,,,,,,,,,
LUIS,Claudio Enrique Merayo Chalico,Urología,,Av. Río Churubusco,,,,,,,,,,,,,
ORALIA,Concepción Patricia del Río Gómez,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Consuelo Cárcamo,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
LUIS,Coral García Rivera,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Cuauhtémoc Villagómez Rodríguez,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
LUIS,Cynthia Peña Vega,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Cynthia Verver Moreno,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Damaris Alejandra Ortiz Núñez,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Daniel Oscar Aguilar,Urología,,Av. Universidad,,,,,,,,,,,,,
TALINA,Daniel Alejandro Arreola Ramírez,Ginecología y Obstetricia,,"Healthec by TecSalud Av. Contreras 300, San Jerónimo Lídice, Magdalena Contreras / Médica Sur",,,,,,,,,,,,,
TALINA,Daniel Calvo Mena,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Daniel Cortés Velázquez,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
LUIS,Daniel Juanxochipiltecatl y Muñoz,Urología,,Capulín,,,,,,,,,,,,,
LUIS,Daniel Quintal Gutiérrez,Urología,,Montecito,,,,,,,,,,,,,
LUIS,Daniel Vieyra Cortés,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Daniela Blancas Camacho,Ginecología y Obstetricia,,"Maravatío 92, Clavería, Azcapotzalco, 02080 Ciudad de México, CDMX",,,,,,,,,,,,,
LUIS,Daniela Charavati,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
LUIS,Danielle Jáuregui Casillas,Ginecología y Obstetricia,,Consultorio privado,,,,,,,,,,,,,
ORALIA,David Ancona Dorantes,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
TALINA,David Fernando Taboada Lozano,Ginecología y Obstetricia,Uroginecología,Hospital MAC Cuemanco,,,,,,,,,,,,,
LUIS,David Islas Cruz,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Delia Virginia Cruz Rodríguez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Denis Lacayo Cabrera,Ginecología y Obstetricia,,Eje 3 Sur 218 Roma Sur,,,,,,,,,,,,,
ANGEL,Diana Cruz Clavel,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
LUIS,Diana de la Paz Theurel,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Diana Iris Hernández,Ginecología y Obstetricia,,Torre Tuxpan 6,,,,,,,,,,,,,
ORALIA,Diana Jiménez González,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
TALINA,Diana Karen Cortés Contreras,Ginecología y Obstetricia,,Hospital MAC Periférico Sur,,,,,,,,,,,,,
ANGEL,Diana Tiro Hernández,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ANGEL,Diógenes Ramírez Palacios,Ginecología y Obstetricia,,Torre Tuxpan 6,,,,,,,,,,,,,
LUIS,Dionisio Mora Hernández,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Dori Rivera,Ginecología y Obstetricia,,Querétaro 58 Roma Norte,,,,,,,,,,,,,
ANGEL,Dr. Palma,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
LUIS,Dulce Dalia Hernández Hernández,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
LUIS,Dulce González Miranda,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Dulce María Camarena Cabrera,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ANGEL,Edgar Arellano,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
LUIS,Edgar Iván Bravo Castro,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Edgar Mendoza Reyes,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Edith Cervantes,Ginecología y Obstetricia,,Torre Tuxpan 10,,,,,,,,,,,,,
ANGEL,Edna Ávila Leguízamo,Ginecología y Obstetricia,,Querétaro,,,,,,,,,,,,,
LUIS,Edna Guzmán Porres,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Eduardo Ordóñez Campos,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Eduardo Paradela,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ANGEL,Edwin Mendoza Ramírez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Efrén Kassim Yaber Gómez,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Elaine Castillo Álvarez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Elba Berenice Alvarado Quiroz,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Eligio Islas Hernández,Ginecología y Obstetricia,,"Calle Callao 693, Lindavista",,,,,,,,,,,,,
LUIS,Elio Rafael Ponce Juárez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Elisa Méndez Álvarez,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Elizabeth Brenda Barando Delgado,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Elizabeth Cacho,Ginecología y Obstetricia,,Manzanillo 100,,,,,,,,,,,,,
ORALIA,Elizabeth Cruz López,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Elizabeth Cruz López,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Elizabeth Jiménez Legaspi,Ginecología y Obstetricia,,"Calle Callao 693, Lindavista",,,,,,,,,,,,,
LUIS,Elizabeth Pérez Torres,Urología,Uroginecología,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Elizabeth Varela Mondragón,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
TALINA,Elly Guerrero Martínez,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Elsa Díaz López,Ginecología y Obstetricia,,Gobernador Gregorio V. 29 Miguel Hidalgo,,,,,,,,,,,,,
LUIS,Elvira Márquez Aguirre,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Emilio Ramírez Garduño,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Emma Carolina Baltazar Guerrero,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Encarnación Jesús Parra Pelcastre,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
ORALIA,Eneyda Martínez Banderas,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
TALINA,Enrique Alfredo Schultz Lanz,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Enrique Martínez,Ginecología y Obstetricia,,,,,,,,,,,,,,,
LUIS,Enrique Reyes Muñoz,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ANGEL,Enrique Rivera Weber,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Enrique Rodríguez Abiita,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Eréndira Guzmán Susana,Urología,,Marcos Carrillo,,,,,,,,,,,,,
TALINA,Eric Iván Trujillo Vázquez,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,Erika Estrada,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Erika Sarai Cruz Amaya,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
LUIS,Erika Valencia,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Ernesto Rodolfo Rivera Medina,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Esther Helga Enríquez Jiménez,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Eugenio Barrera Pérez,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Evangelina Valdovinos Cervantes,Ginecología y Obstetricia,,Montiel,,,,,,,,,,,,,
ANGEL,Evelio Cabezas García,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Fabiola Rivera Silvia,Ginecología y Obstetricia,,Av. Periférico Sur,,,,,,,,,,,,,
ANGEL,Fabiola Rojas Gonzáles,Ginecología y Obstetricia,,Torre Durango 64,,,,,,,,,,,,,
LUIS,Fátima Girón Ávila,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Fausto Jonatan Balanzario Cuevas,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
TALINA,Federico Bertrand Noriega,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Federico Bertrand Noriega,Urología,,Camino a Santa Teresa,,,,,,,,,,,,,
LUIS,Felipe Alfán Guzmán,Ginecología y Obstetricia,,Av. Patriotismo,,,,,,,,,,,,,
ORALIA,Félix Martínez Moreno,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Ginecología y Obstetricia,Ginecología y Obstetricia,,"Homero 1425, Polanco",,,,,,,,,,,,,
ORALIA,Fernanda Linares,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
ANGEL,Fernando de Jesús Ruiz García,Urología,,Querétaro,,,,,,,,,,,,,
LUIS,Fernando Desales González,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Fernando Emmanuel Garduño Valle,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Fernando González Meza García,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Fernando López Martínez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Fernando López Reyes,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Fernando Ruiz,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
TALINA,Florencia Covarrubias Haiek,Ginecología y Obstetricia,,Hospital Ángeles Pedregal,,,,,,,,,,,,,
ANGEL,Fragoso Hernández Mario,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
LUIS,Francis Erika Angulo Rujano,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
TALINA,Francisco Abel Martínez Ávila,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Francisco González Partida,Ginecología y Obstetricia,,Camino a Santa Teresa,,,,,,,,,,,,,
ORALIA,Francisco Javier Alvarado Gay,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Francisco Javier Borrajo Carvajal,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Francisco Javier Díaz Rivas,Ginecología y Obstetricia,,Av. Dr. Gustavo Baz 309-TR A1,,,,,,,,,,,,,
ANGEL,Francisco Javier Gudiño Molina,Ginecología y Obstetricia,,Torre Durango 49,,,,,,,,,,,,,
ANGEL,Francisco Javier Hernández Daniel,Urología,,Bajío,,,,,,,,,,,,,
TALINA,Francisco Manuel Bustamante Romero,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Gabriel Gallo,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ANGEL,Gabriel Quinto Catalán,Urología,,Frontera,,,,,,,,,,,,,
ANGEL,Gabriela Alma Consuelo,Ginecología y Obstetricia,,Tuxpan,,,,,,,,,,,,,
ORALIA,Gabriela Angélica Zavala Acosta,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Gabriela Arredondo Vázquez,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ORALIA,Gabriela Berenice Varga Gutiérrez,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
ANGEL,Gabriela Berenice Vázquez de la Peña,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Gabriela Elisa Espinosa Vázquez,Ginecología y Obstetricia,,"Viveros de Uman 28, colonia Viveros del Valle Tlalnepantla",,,,,,,,,,,,,
LUIS,Gamaliel Rodríguez Reyes,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Gerardo Andrés Alba Jasso,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Gerardo Espinosa Esparza,Ginecología y Obstetricia,,Montecito,,,,,,,,,,,,,
TALINA,Gerardo Fernández Noyola,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Gerardo Gorostizaga González,Ginecología y Obstetricia,,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
ANGEL,Gerardo Méndez Espinoza,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Gerardo Quiroz Garza,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
ORALIA,Gerardo Reyes Díaz,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
TALINA,Gerardo Tena González Méndez,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Gerardo Tinoco Jaramillo,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Germán Gabriel Palacios López,Ginecología y Obstetricia,,Av. Lomas Verdes,,,,,,,,,,,,,
TALINA,Gilberto Tena Alavez,Ginecología y Obstetricia,,Periférico Sur,,,,,,,,,,,,,
ORALIA,Guillermo Nájera González,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Giselle Lozano Alcocer,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Gloria Elena Cruz Piñones,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
LUIS,Gloria Elena Rivero Song,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Gómez Reyes Ma. Ileana,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Gonzalo Esteban Pol Kippes,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Gonzalo Morán,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
LUIS,Griselda Martínez Aragón,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Griselda Pérez Alcántara,Ginecología y Obstetricia,,Montecito,,,,,,,,,,,,,
LUIS,Guadalupe Cabrera Toledo,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
LUIS,Guadalupe Guerrero Reyes,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Guadalupe Ramírez Cedillo,Ginecología y Obstetricia,,Montecito,,,,,,,,,,,,,
ANGEL,Guillermina Argüelles,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
ANGEL,Guillermina Ramírez Argüelles,Ginecología y Obstetricia,,Tuxpan,,,,,,,,,,,,,
ORALIA,Guillermo Alejandro Goitita,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Guillermo Goitia Landeros,Ginecología y Obstetricia,Biología de la Reproducción,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Guillermo Moreno Flores,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
TALINA,Gustavo Adolfo Durán Hernández,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Gutiérrez Ramírez Antonio,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Harold Bigmad Villarroel López,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
LUIS,Héctor Iván Guerra Malacara,Ginecología y Obstetricia,,Consultorio privado,,,,,,,,,,,,,
ORALIA,Héctor Peña Dehesa,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Héctor Rodríguez Aguilar,Ginecología y Obstetricia,,Eje 3 Sur 218 Roma Sur,,,,,,,,,,,,,
TALINA,Héctor Sandoval Barba,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Helio Ponce,Ginecología y Obstetricia,,Querétaro 58 Roma Norte,,,,,,,,,,,,,
ANGEL,Hermisenda María Bermúdez,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
ANGEL,Hilary Núñez Araujo,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Hugo Ernesto Alejos Garduño,Ginecología y Obstetricia,,Eje 3 Sur 218 Roma Sur,,,,,,,,,,,,,
ORALIA,Hugo Salamanca Ordóñez,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Hugo Salazar Ramírez,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Humberto Ortiz Rodríguez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Idalia Hernández Karla,Ginecología y Obstetricia,,Enrique Sada Muguerza,,,,,,,,,,,,,
ORALIA,Ignacio Eduardo Eguiarte,Ginecología y Obstetricia,,Manuel E. Izaguirre,,,,,,,,,,,,,
ANGEL,Ignacio Morales Álvarez,Ginecología y Obstetricia,,Eje 3 Sur 218 Roma Sur,,,,,,,,,,,,,
ORALIA,Ilse Guadalupe de Jesús Cerón,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
ANGEL,Imelda Acosta,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
LUIS,Indhira Azucena García Banda,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
LUIS,Indira Jiménez Radilla,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Isaías Preciado Abril del Carmen,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ANGEL,Ismael González Julio,Urología,,Tuxpan,,,,,,,,,,,,,
LUIS,Isaac Rodríguez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Iván Castro Edgar,Urología,,Av. Lomas Verdes,,,,,,,,,,,,,
LUIS,Iván Ruiseco Herrera,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
TALINA,Jaime Claudio Granados Marín,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Jaime Uscanga Yépez,Urología,,Prl. Paseo de la Reforma,,,,,,,,,,,,,
LUIS,Janeth Marín Hernández,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Janeth Márquez Acosta,Ginecología y Obstetricia,Biología de la Reproducción,San Ángel Inn Universidad,,,,,,,,,,,,,
ANGEL,Javier Francisco Gudiño Molina,Ginecología y Obstetricia,,Durango,,,,,,,,,,,,,
LUIS,Jenifer Alejandra Bustamante Mendoza,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ANGEL,Jenifer Reyes,Ginecología y Obstetricia,,Querétaro 58 Roma Norte,,,,,,,,,,,,,
ORALIA,Jesús Macías Duvignau,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Jessica Abril Rosas Álvarez,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Jessica Aidé Mora Galván,Ginecología y Obstetricia,,Capital Medical Center,,,,,,,,,,,,,
LUIS,Jesús Cisneros,Ginecología y Obstetricia,Biología de la Reproducción,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Jesús José González Avendaño,Ginecología y Obstetricia,,Río Bamba,,,,,,,,,,,,,
ORALIA,Jesús José González Avendaño,Ginecología y Obstetricia,,Av. Lomas Verdes,,,,,,,,,,,,,
LUIS,Jonadad Jasso Jiménez,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Jonathan Astudillo Ibarrondo,Ginecología y Obstetricia,,Torre Durango 64,,,,,,,,,,,,,
ORALIA,Jorge Arturo Esparza Iturbe,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ANGEL,Jorge Barbosa Vilchis,Ginecología y Obstetricia,,Torre Tuxpan 10,,,,,,,,,,,,,
LUIS,Jorge Carlos López Vallejo Castro,Urología,,Av. Universidad,,,,,,,,,,,,,
ANGEL,Jorge Jaspersen Gastelum,Urología,,Querétaro,,,,,,,,,,,,,
ORALIA,Jorge Lezama,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ANGEL,Jorge Luis Vega Cuevas,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Jorge Morales,Ginecología y Obstetricia,,"Calz. Azcapotzalco - La Villa 10, Col del Maestro, Azcapotzalco, 02040 Ciudad de México, CDMX",,,,,,,,,,,,,
TALINA,Jorge Moreno Palacios,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Ana Cristina Ramírez Echeverría,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ANGEL,Blanca Estela Vega,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ANGEL,Jorge Urtado Conde,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Jorge Villavicencio Castañeda,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,José Alfredo Ruiz,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
TALINA,José Alfredo Zúñiga Montiel,Ginecología y Obstetricia,,Calz. Acoxpa,,,,,,,,,,,,,
TALINA,José Alfredo Zúñiga Montiel,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,José Antonio Ramírez Calvo,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,José Carlos Guerrero Dorado,Ginecología y Obstetricia,,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
ORALIA,José Carlos Salazar,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
LUIS,José Daniel Flores Alatriste,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,José de Jesús del Real,Ginecología y Obstetricia,,"Homero 530, Polanco",,,,,,,,,,,,,
ORALIA,José de Jesús González Avendaño,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ANGEL,José Fugarolas Marín,Ginecología y Obstetricia,,Torre Tuxpan 10,,,,,,,,,,,,,
TALINA,José Gómez Sánchez,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,José Gustavo Martínez Lugo,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,José Humberto Ocampo Mazariegos,Ginecología y Obstetricia,,Cozumel 62 Roma Norte,,,,,,,,,,,,,
LUIS,José Javier Melo Camacho,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,José Jesús Macías Duvignau,Ginecología y Obstetricia,,Av. Chapultepec,,,,,,,,,,,,,
TALINA,José Juan Valdés García,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,José Luis Peñuluri Santoyo,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
LUIS,José Manuel García Wrooman,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
TALINA,José Manuel Huerta Hentschel,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,José Manuel Lorenzo,Ginecología y Obstetricia,,Querétaro 58 Roma Norte,,,,,,,,,,,,,
ANGEL,José María Meza,Ginecología y Obstetricia,,Torre Tuxpan 16,,,,,,,,,,,,,
LUIS,José Miguel Navarro Martín,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,José Miguel Reyes Garita,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
TALINA,José Ramón Vírez Ruiz,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,José Roberto Silvestri Tomassani,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,José Rodrigo Aquino,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,José Ruiz Medina,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Joseph Arturo Rosa Córdova,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
TALINA,Josué Christian Hernández Bañales,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Juan Carlos Barros Delgadillo,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Juan Carlos de León Carbajal,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Juan Carlos Izquierdo Puente,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Juan Carlos Negrete,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Juan Ernesto Sánchez Tapia,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Juan Francisco Méndez Sánchez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Juan Gabriel Pérez Vázquez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Juan Hurtado Gorostieta,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Juan Ignacio Monjarás Guerra,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Juan Ignacio Stenner Pérez Gavilán,Urología,,Puente de Piedra,,,,,,,,,,,,,
TALINA,Daniel Fabián Ramírez Moreno,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Juan Jiménez Huerta,Ginecología y Obstetricia,,Durango,,,,,,,,,,,,,
ORALIA,Deborah Marín Robles,Ginecología y Obstetricia,,"Calle Callao 693, Lindavista",,,,,,,,,,,,,
ORALIA,Juan José Gorostizaga Lezama,Ginecología y Obstetricia,,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
LUIS,Juan José Solano Pérez,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Edna Ávila,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
ORALIA,Eduardo Nieto Vázquez,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Juan Madrazo Rodríguez,Ginecología y Obstetricia,,Torre Durango 64,,,,,,,,,,,,,
ORALIA,Juan Manuel Hernández Herrera,Ginecología y Obstetricia,,"Alexander Von Humboldt 88, Lomas Verdes 3ra Secc, 53120 Naucalpan de Juárez, Méx",,,,,,,,,,,,,
TALINA,Juan Manuel Ochoa López,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Juan Muñoz Xochipiltecatl Daniel,Urología,,"Capulín 46, Int. 211, Benito Juárez",,,,,,,,,,,,,
TALINA,Juan Osvaldo Cuevas Alpuche,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Judith Naranjo Sánchez,Ginecología y Obstetricia,,Av. Contreras,,,,,,,,,,,,,
ORALIA,Judith Yasmin Pallares,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Julián Velázquez Fonseca,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ANGEL,Julieta Gutiérrez Zamora,Ginecología y Obstetricia,,Torre Tuxpan 10,,,,,,,,,,,,,
ORALIA,Julio Camacho,Ginecología y Obstetricia,,"Petrarca 133, Polanco",,,,,,,,,,,,,
ORALIA,Karelia Mendoza Baranda,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
ORALIA,Karen Josseline Delgado,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Karen Pérez Valdez,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ORALIA,Karen Viviana Limón Rodríguez,Ginecología y Obstetricia,,Av. Sor Juana Inés de la Cruz,,,,,,,,,,,,,
LUIS,Karina Pérez Sousa,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Karla Carmona Bravo,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Karla Cecila Font López,Ginecología y Obstetricia,,Torre Durango 64,,,,,,,,,,,,,
ORALIA,Karla Libeth Michorena Sarmiento,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Karla María Bujalil Montero,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
ANGEL,Karla Moreno,Ginecología y Obstetricia,,Torre Tuxpan 6,,,,,,,,,,,,,
ANGEL,Karla Osiris Peña Peláez,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
ORALIA,Karla Renee Arau Contreras,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Karla Rodríguez,Ginecología y Obstetricia,,"Av. Clavería 154, Clavería, Azcapotzalco, 06910 Ciudad de México, CDMX",,,,,,,,,,,,,
LUIS,Kenia Lizeth Benítez Castro,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Laura Coretta Mejiario,Urología,,Durango,,,,,,,,,,,,,
LUIS,Laura García Moreno,Ginecología y Obstetricia,,Montecito,,,,,,,,,,,,,
TALINA,Laura Hernández Gurrola,Ginecología y Obstetricia,Biología de la Reproducción,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,Laura Reyes Ramírez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ANGEL,Laura Romero Rodríguez,Ginecología y Obstetricia,,Tepic 114,,,,,,,,,,,,,
ORALIA,Laura Romero Rodríguez,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
LUIS,Gabriela León Flores,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Ignacio Reyes Urrutia,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Lauro Manuel Loria Casanova,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
TALINA,Lenin Rojas Buendía,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Leonardo Ávila Lizárraga,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
LUIS,Leonardo Isais Romero López,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ORALIA,Leonel Alfonso,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ORALIA,Leonor Sarahi Martínez Mejía,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Leopoldo Alejandro Vázquez Estrada,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Leopoldo Gatica Galina,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ORALIA,Leopoldo Río de la Loza,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Leopoldo Río de la Loza Cava,Ginecología y Obstetricia,,"Alexander Von Humboldt 88, Lomas Verdes 3ra Secc, 53120 Naucalpan de Juárez, Méx",,,,,,,,,,,,,
ORALIA,Lesli Pamela González Domínguez,Ginecología y Obstetricia,,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
ANGEL,Leslie Eunice Omaña Yoval,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ANGEL,Leticia Guadarrama,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
LUIS,Leticia Natalie Gómez Martínez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Liliana Caballero Castañeda,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ORALIA,Liliana Fernández,Ginecología y Obstetricia,,"Av. Montevideo 303, Lindavista",,,,,,,,,,,,,
ANGEL,Liliana Morales Domínguez,Ginecología y Obstetricia,,Querétaro 58 Roma Norte,,,,,,,,,,,,,
LUIS,Liliana Nohemí Arzate Mena,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Liliana Oropeza Chávez,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
ORALIA,Limón Rodríguez Karen Viviana,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Linda Pamela Hernández Rodríguez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Linet Ponce Ramírez,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
TALINA,Lino Amor Calleja,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Lizbeth Martínez Portugal,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
TALINA,Lizette Manzo Carrillo,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
TALINA,Lizette Pérez Hernández,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Lorena Montoya Sánchez,Ginecología y Obstetricia,,"Homero 527, tercer piso",,,,,,,,,,,,,
LUIS,Lorena Ponce Jiménez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Lorena Ponce Jiménez,Ginecología y Obstetricia,,Río Churubusco,,,,,,,,,,,,,
LUIS,Lorena Romero,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Lorena Sánchez Basurto,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Lourdes Sofía Gómez Inclán,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ORALIA,Lucía Angélica Reyes Ramírez,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Lucía Itzel Vázquez Ferrero,Ginecología y Obstetricia,,Gobernador Gregorio V. 29 Miguel Hidalgo,,,,,,,,,,,,,
ORALIA,Luciano Coquis González,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
ORALIA,Luciano Coquis González,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Lucrecia García Hernández,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Lucrecia García Hernández,Ginecología y Obstetricia,,Cuauhtémoc,,,,,,,,,,,,,
LUIS,Lucrecia Hernández Bolaños,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ORALIA,Luis Alberto Mendoza Álvarez,Ginecología y Obstetricia,,"Av. Lomas Verdes 2165, Naucalpan",,,,,,,,,,,,,
ANGEL,Luis Claudio Eri de Hernández,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Luis Eligio Espinoza Hernández,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
TALINA,Luis Ernesto Gallardo Valencia,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Luis Fernando Quinzaños Sordo,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Luis G. Senties Cortina,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ANGEL,Luis Manuel Ruiz Carapia,Ginecología y Obstetricia,,Tepic 139,,,,,,,,,,,,,
LUIS,Luis Pérez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Luis Rodrigo Guarneros Valdovinos,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Luisa Patricia Hernández,Ginecología y Obstetricia,,Eje 3 Sur 218 Roma Sur,,,,,,,,,,,,,
ORALIA,Luz Elena Aguilar Segura,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
LUIS,Luz Elizabeth Turrubiate Munguía,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ANGEL,Luz María Sánchez Hdez,Ginecología y Obstetricia,,Torre Tuxpan 8,,,,,,,,,,,,,
ANGEL,Magalhi Guadalupe Robledo,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Magda Icel Salgado Jacobo,Ginecología y Obstetricia,,Av. Primero de Mayo,,,,,,,,,,,,,
TALINA,Malenys Sánchez,Ginecología y Obstetricia,,Hospital MAC Periférico Sur,,,,,,,,,,,,,
LUIS,Jessica Jazmín Chávez,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Jorge Alberto Campos Cañas,Ginecología y Obstetricia,Biología de la Reproducción,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Manuel de Jesús Arriola Zamarripa,Ginecología y Obstetricia,,Río Bamba,,,,,,,,,,,,,
ANGEL,Manuel Gómez Rodríguez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Manuel Lozano,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ORALIA,Manuel Ramos Garduza,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Marcela González Espejel,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
TALINA,Marco Antonio Pérez Cisneros,Ginecología y Obstetricia,,Periférico Sur,,,,,,,,,,,,,
ANGEL,Margarita Elizabeth Flores Zaleta,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,María Belem Martínez Romero,Ginecología y Obstetricia,,Montecito,,,,,,,,,,,,,
TALINA,María de la Caridad Carranco Salinas,Ginecología y Obstetricia,,Hospital Ángeles Pedregal Con 715 D,,,,,,,,,,,,,
ANGEL,María de los Ángeles Pérez Ramírez,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ANGEL,María del Carmen Martínez Chiñas,Ginecología y Obstetricia,,Tepic 139,,,,,,,,,,,,,
ANGEL,María del Carmen Pérez Reyes,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,María del Pilar Velázquez Sánchez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,María Digna Nava Barahona,Ginecología y Obstetricia,,"Temístocles 210, Polanco IV Secc, CDMX",,,,,,,,,,,,,
ORALIA,María Dolores Alarcón Alcántara,Ginecología y Obstetricia,,Enrique Sada Muguerza 17,,,,,,,,,,,,,
ANGEL,María Eugenia Gonzales Morales,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
LUIS,María Fernanda Fernández Corzas,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,María Fernanda Río de la Loza,Ginecología y Obstetricia,,"Alexander Von Humboldt 88, Lomas Verdes 3ra Secc, 53120 Naucalpan de Juárez, Méx",,,,,,,,,,,,,
ANGEL,María Isabel Pérez Ortega,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,María José Rodríguez Gutiérrez,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ANGEL,María Juana Hernández Valencia,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ANGEL,María Julieta Hernández Cummings,Ginecología y Obstetricia,,Torre Tepic 113,,,,,,,,,,,,,
LUIS,María Luisa Fuentes,Ginecología y Obstetricia,,Consultorio privado,,,,,,,,,,,,,
LUIS,María Rossana Valiente Aguilar,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,María Teresa Méndez Gómez,Ginecología y Obstetricia,,Tuxpan 39,,,,,,,,,,,,,
ANGEL,María Teresa Solano,Ginecología y Obstetricia,,Manzanillo 101,,,,,,,,,,,,,
TALINA,María Victoria Marchese,Ginecología y Obstetricia,,"Paseo de los Tamarindos 384 P9, Col. Bosques de las Lomas, Cuajimalpa de Morelos",,,,,,,,,,,,,
ANGEL,Maribel Ibarra Sarlatcons,Ginecología y Obstetricia,,Tepic 116,,,,,,,,,,,,,
ANGEL,Maricruz Barraza,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
LUIS,Maricruz Dañino Montes,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Mario Alberto Ramírez Negrón,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Mario Antonio López Salas,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ANGEL,Mario Garay Enríquez,Ginecología y Obstetricia,,Río Pánuco,,,,,,,,,,,,,
ORALIA,Mario Lugo Rangel,Urología,,Vía Gustavo Baz Prada,,,,,,,,,,,,,
ANGEL,Mario Martínez Ruiz,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Marisol Ayala Juárez,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Marisol Rivera Hernández,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
TALINA,Marlene de la Peña Gutiérrez,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,Marlene Lizbeth Zamora Ramírez,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Martha Espinoza Esparza,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Martha Leticia Zancatl Díaz,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
TALINA,Martha Lilia Rodríguez García,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
TALINA,Martha Olivia Gómez Alvarado,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Martha Susana Macías Galván,Ginecología y Obstetricia,,Av. Chapultepec,,,,,,,,,,,,,
ORALIA,Jorge Siller Nieto,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
TALINA,Mauricio Cantellano Orozco,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ORALIA,Mauricio Mancilla Castelán,Ginecología y Obstetricia,,Cto. Juristas,,,,,,,,,,,,,
ANGEL,Mauricio Marx Orta,Ginecología y Obstetricia,,Torre Querétaro,,,,,,,,,,,,,
TALINA,Mauricio Osorio Caballero,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Mercedes del Pilar Álvarez Goris,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Mervin Omar Bolívar Cuencas,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Miguel Ángel Zapata Villalba,Urología,,Av. Sor Juana Inés de la Cruz,,,,,,,,,,,,,
TALINA,Miguel Ángel López Valle,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Miguel Ángel Maldonado,Ginecología y Obstetricia,,Consultorio privado,,,,,,,,,,,,,
ANGEL,Miguel Ángel Robles Carmona,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Miguel Ángel Ulloa,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ANGEL,Miguel Ángel Walter Tordecillas,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
LUIS,Miguel Castañeda Héctor,Urología,,Av. Chapultepec,,,,,,,,,,,,,
ANGEL,Miguel Corres Molina,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
LUIS,Miguel Corres Molina,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
TALINA,Milagros Clementina Pérez Quintanilla,Ginecología y Obstetricia,,"Carlos Graef Fernández 154-342 (Tlaxala Santa Fe - Consultorio 342), Cuajimalpa de Morelos",,,,,,,,,,,,,
ORALIA,Mireya Ovando Tapia,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Miriam Azenet Carvajal González,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Juan Jiménez Huerta,Ginecología y Obstetricia,,Torre Durango VIS 50,,,,,,,,,,,,,
ANGEL,Juan Luis Aboites,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ORALIA,Mónica Mejía Vargas,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Mónica Patrón Mondragón,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
LUIS,Mónica Rodríguez León,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Montserrat Ariadna del Castillo Rodríguez,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Montserrat Cuevas,Ginecología y Obstetricia,,Av. Dr. Gustavo Baz 309-TR A1,,,,,,,,,,,,,
ORALIA,Myrna Flores Mercado,Ginecología y Obstetricia,,Casma,,,,,,,,,,,,,
ORALIA,Nancy Román Estrada,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
TALINA,Narciso Hernández Toriz,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Navarrete Horta Teresa,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
LUIS,Nayeli Córdoba Jiménez,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ORALIA,Nayeli Martínez Jaime,Ginecología y Obstetricia,,"Calle Matanzas 715, Lindavista",,,,,,,,,,,,,
ORALIA,Nelly Cortina,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
ANGEL,Nesi Pedraza,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ANGEL,Nicolás Salva Paster,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
LUIS,Noemí Raquel Guerrero Patiño,Ginecología y Obstetricia,Biología de la Reproducción,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Norma Angélica Hernández Pineda,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
TALINA,Norma Lilia Ramírez Velázquez,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Norma Patricia Trejo,Ginecología y Obstetricia,,Torre Tuxpan 54,,,,,,,,,,,,,
ANGEL,Octavio Cedillo Ley,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Oliver Paul Cruz Orozco,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
TALINA,Olivia Natividad López Adame,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Olivia Peña Ballesteros,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
ANGEL,Olivia Salas,Ginecología y Obstetricia,,Torre Tuxpan 6,,,,,,,,,,,,,
ANGEL,Omar Dimas Victorio Vargas,Urología,,Marcos Carrillo,,,,,,,,,,,,,
ORALIA,Oscar Mejía Mendoza,Ginecología y Obstetricia,,Av. Dr. Gustavo Baz 309-TR A1,,,,,,,,,,,,,
ORALIA,Oscar Moncada Navarro,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
ORALIA,Oscar Rubén Guinto Martiarena,Ginecología y Obstetricia,,"Av. Montevideo 303, Lindavista",,,,,,,,,,,,,
ORALIA,Oscar Salvador Sánchez Vázquez,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
LUIS,Pablo Mariano González Aldeco,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
TALINA,Paloma de la Torre y Fernández,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ORALIA,Paola Alejandra Vázquez García,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
TALINA,Paola Delfina Rodríguez Estrada,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Patricia del Carmen Franco Castañeda,Ginecología y Obstetricia,,Consultorio privado,,,,,,,,,,,,,
LUIS,Patricia Orielle Ponce Licera,Ginecología y Obstetricia,,Montecito,,,,,,,,,,,,,
ANGEL,Patricia Pérez Bailón,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ANGEL,Patricia Pérez Bailón,Ginecología y Obstetricia,,Tlacotalpan,,,,,,,,,,,,,
TALINA,Patricio Cruz García Villa,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Paulet Renne Flores Zárate,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
LUIS,Paulett Bayona Soriano,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Paulina Carpio Bárcenas,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Paulina González Peña,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Paulina Jancor,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ORALIA,Paulina Treviño,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ORALIA,Paulina Treviño Villarreal,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Laura Vanessa Rodríguez Rocha,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Manuel Alonso Villegas Martínez,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Perla Denisse Aguilar,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Priscilla Roque Gutiérrez,Ginecología y Obstetricia,Biología de la Reproducción,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Rachel Firsman Amora,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Rafael Alberto García Gudiño,Ginecología y Obstetricia,,Tepic 117,,,,,,,,,,,,,
TALINA,Ramiro Ordaz Vega,Ginecología y Obstetricia,Biología de la Reproducción,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Ramón Celaya Barrera,Ginecología y Obstetricia,,Torre Durango 290,,,,,,,,,,,,,
ANGEL,Ranferi Gaona Arreola,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
TALINA,Raúl Alonso Martínez Ayala,Ginecología y Obstetricia,,Hospital MAC Cuemanco,,,,,,,,,,,,,
ORALIA,Raúl Antonio León Ochoa,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
ORALIA,Raúl Barrientos Mendoza,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ORALIA,Raúl Padilla Rodas,Ginecología y Obstetricia,,Av. Dr. Gustavo Baz 309-TR A1,,,,,,,,,,,,,
ORALIA,Raúl Padilla Rodas,Ginecología y Obstetricia,,Av. Gustavo Baz Prada,,,,,,,,,,,,,
LUIS,Raymundo Bernal García,Urología,,Av. Universidad,,,,,,,,,,,,,
LUIS,Raymundo Bernal García,Urología,,Av. Árbol del Fuego,,,,,,,,,,,,,
LUIS,Mónica Alejandra Matta Martínez,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
TALINA,Raymundo Canales de la Fuente,Ginecología y Obstetricia,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Renata Madrid Zavala,Ginecología y Obstetricia,Biología de la Reproducción,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Renata Melina Madrid Zavala,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,René Hernández Sánchez,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Reyna Erika Franco Laguna,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Perla Angélica Silva Palma,Ginecología y Obstetricia,,Hospital MAC Cuemanco,,,,,,,,,,,,,
LUIS,Reyna Laura López Sánchez,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Reyna Mariel Maclu Zorrero,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
TALINA,Ricardo Adame Pinacho,Ginecología y Obstetricia,,"Hospital Ángeles Pedregal Camino a Sta. Teresa 1055-S Torre Ángeles Piso 7 Consultorio 730,",,,,,,,,,,,,,
TALINA,Ricardo Almeida Magaña,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
LUIS,Ricardo Alvarado Ballinas,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Ricardo Careaga Benítez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Ricardo Jáuregui Tejeda,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
ORALIA,Rivero Corona Juan,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
TALINA,Roberto Alejandro Carlos Romero y Lomas,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
TALINA,Roberto Alejandro Carlos Romero y Lomas,Ginecología y Obstetricia,,Calz. Acoxpa,,,,,,,,,,,,,
ANGEL,Roberto Carlos Manríquez Angulo,Ginecología y Obstetricia,,Av. Chapultepec,,,,,,,,,,,,,
LUIS,Roberto Carmona Librado,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Roberto Cisneros Chávez,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Roberto Martínez Álvarez,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
ANGEL,Rocío Guerra Arias,Ginecología y Obstetricia,,Torre Tuxpan 10,,,,,,,,,,,,,
LUIS,Rocío Velázquez Falconi,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Rodolfo Leonel Vargas Ruiz,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ANGEL,Rodrigo Emilio Ruiz Barrios,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Rodrigo Emilio Ruz Barros,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
TALINA,Rodrigo León Mar,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
TALINA,Rodrigo Pérez Becerra,Urología,,Calz. Acoxpa,,,,,,,,,,,,,
TALINA,Rodrigo Pérez Becerra,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Rodrigo Silva,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
TALINA,Romina Elizabeth Schäfer Vega,Ginecología y Obstetricia,,"Hospital Ángeles Lomas Vialidad de la Barranca, S/N, Valle de las Palmas, Huixquilucan",,,,,,,,,,,,,
LUIS,Rosa Elba Mendoza Morales,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Rosa Elena Cano Nava,Ginecología y Obstetricia,,Av. Dr. Gustavo Baz 309-TR A1,,,,,,,,,,,,,
ANGEL,Rosa Estela Rodríguez,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
ANGEL,Rosa María,Ginecología y Obstetricia,,Manzanillo 102,,,,,,,,,,,,,
ANGEL,Rosa María Arce,Ginecología y Obstetricia,,Torre Durango VIS 50,,,,,,,,,,,,,
ANGEL,Rosa María Chi Rodríguez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Rosa María Sánchez,Ginecología y Obstetricia,,"Homero 527, tercer piso",,,,,,,,,,,,,
ORALIA,Rosa María Tufiño Loza,Ginecología y Obstetricia,,"Av. Montevideo 303, Lindavista",,,,,,,,,,,,,
LUIS,Rosa Virginia Sandoval Pirela,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
LUIS,Rosalía García Ruiz,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ANGEL,Rossana Argentina Vidal Ramírez,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
ORALIA,Rossana Argentina Vidal Ramírez,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
ANGEL,Rubén Saurer Ramírez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Ruth Camargo Lavaverde,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Salvador Daniel,Ginecología y Obstetricia,,Torre Tepic 113,,,,,,,,,,,,,
ANGEL,Salvador Daniel Carapia,Ginecología y Obstetricia,,Tepic 118,,,,,,,,,,,,,
LUIS,Salvador Gaviño Ambriz,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
ANGEL,Sánchez,Ginecología y Obstetricia,,Cozumel 62 Roma Norte,,,,,,,,,,,,,
ANGEL,Sandra Adriana Vera Vázquez,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Sandra Flores Lozada,Ginecología y Obstetricia,,"Av. Montevideo 303, Lindavista",,,,,,,,,,,,,
ORALIA,Sandra Gabriela Rule Gómez,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
TALINA,Sandra Guadalupe Girón Vargas,Ginecología y Obstetricia,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
LUIS,Sandra Iveth Ramírez Pastrana,Ginecología y Obstetricia,,Centro de Especialidades Mixcoac,,,,,,,,,,,,,
ANGEL,Sandra Uribe Flores,Ginecología y Obstetricia,,Tepic 113,,,,,,,,,,,,,
ANGEL,Sandra Uribe Flores,Ginecología y Obstetricia,,Torre Tepic 113,,,,,,,,,,,,,
LUIS,Sandra Vera,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
TALINA,SanJuan Padrón Lucio,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
ANGEL,Santiago Islas Escoto,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Santos Regino Uscanga Sánchez,Ginecología y Obstetricia,,"Circuito Misioneros 5, Ciudad Satélite",,,,,,,,,,,,,
LUIS,Sara Calvillo,Ginecología y Obstetricia,Biología de la Reproducción,Consultorio privado,,,,,,,,,,,,,
LUIS,Saúl Guzmán Laguna,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
TALINA,Sergio Durán Ortiz,Urología,,Hospital Ángeles Acoxpa,,,,,,,,,,,,,
TALINA,Sergio Durán Ortiz,Urología,,Hospital MAC Periférico Sur,,,,,,,,,,,,,
ANGEL,Sergio Isrrael García Navarro,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ANGEL,Sergio Martín Velasco Alva,Ginecología y Obstetricia,,Cozumel 62 Roma Norte,,,,,,,,,,,,,
ORALIA,Sergio Pedraza,Ginecología y Obstetricia,,"Ejército Nacional 613, Polanco",,,,,,,,,,,,,
ANGEL,Silvia Escalera,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ANGEL,Sonia Reynoso Ramírez,Ginecología y Obstetricia,,Frontera 74 Roma Norte,,,,,,,,,,,,,
LUIS,Stephanie Galicia López,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
LUIS,Susana Haquet,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
TALINA,Sylvain Collura Merlier,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Talina Ramírez Caro,Ginecología y Obstetricia,,Tepic 139,,,,,,,,,,,,,
ORALIA,Tania Piña,Ginecología y Obstetricia,,"Calle Casma 690, Lindavista",,,,,,,,,,,,,
LUIS,Teresa Martínez Guerrero,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ORALIA,Teresa Michel Morales Montiel,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Teresa Navarrete Horta,Ginecología y Obstetricia,,Tehuantepec 251,,,,,,,,,,,,,
ORALIA,Teresa Rojas Sánchez,Ginecología y Obstetricia,,"Río Bamba 639, Lindavista",,,,,,,,,,,,,
LUIS,Valeria Ventura Quintana,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
ANGEL,Venancia Vázquez Nolasco,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
LUIS,Verónica del Moral Estrada,Ginecología y Obstetricia,,San Ángel Inn Universidad,,,,,,,,,,,,,
LUIS,Verónica Diez Martínez Tara,Ginecología y Obstetricia,,MAC La Viga,,,,,,,,,,,,,
ANGEL,Verónica Lara Vaca,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
LUIS,Verónica Martínez Ramírez,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
ANGEL,Verónica Muñoz,Ginecología y Obstetricia,,"Querétaro 156, Roma Norte",,,,,,,,,,,,,
ANGEL,Vicente Rodríguez,Ginecología y Obstetricia,,Torre Tuxpan 45 A,,,,,,,,,,,,,
ANGEL,Víctor Hugo Carmona Ornelas,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
ORALIA,Víctor Hugo Ortega Pérez,Ginecología y Obstetricia,,Río Bamba 639. Lindavista,,,,,,,,,,,,,
TALINA,Víctor Israel Victoria Mejía,Urología,,Hosp. Ángeles del Pedregal,,,,,,,,,,,,,
ANGEL,Víctor Manuel Topele Carmona,Ginecología y Obstetricia,,Cda. Agrarismo 208 Escandón Miguel H.,,,,,,,,,,,,,
ORALIA,Violeta Fabiola Machuca Hernández,Ginecología y Obstetricia,,"Sor Juana Inés de la Cruz 280, Tlalnepantla",,,,,,,,,,,,,
ANGEL,Virginia Cortés Uribe,Ginecología y Obstetricia,,Tlacotalpan 59 Roma Sur,,,,,,,,,,,,,
LUIS,Virginia Espinosa Delgado,Ginecología y Obstetricia,,Insurgentes Sur,,,,,,,,,,,,,
TALINA,Vitelio Ruiz Bock,Ginecología y Obstetricia,,Hospital MAC Periférico Sur,,,,,,,,,,,,,
LUIS,Waldemar Alejandro Solís Loria,Ginecología y Obstetricia,,Av. Chapultepec,,,,,,,,,,,,,
ANGEL,Xochiquetzal Sandra Cruz,Urología,,Marcos Carrillo,,,,,,,,,,,,,
ANGEL,Yamil Ernesto Ojeda Morales,Ginecología y Obstetricia,,Torre Durango 64,,,,,,,,,,,,,
LUIS,Yamile Torres Jasso,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
LUIS,Yasiu Bustamante Quan,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
TALINA,Yasmín Miranda Aguilar,Ginecología y Obstetricia,,Av. Canal de Miramontes,,,,,,,,,,,,,
LUIS,Yazmín Hernández Balderas,Ginecología y Obstetricia,,Ángeles Universidad,,,,,,,,,,,,,
ORALIA,Yedid Medina Nava,Ginecología y Obstetricia,,"Circuitos Centro Comercial 20, Tlalnepantla",,,,,,,,,,,,,
LUIS,Yeni Lovera,Ginecología y Obstetricia,,Clínica Santa Margarita,,,,,,,,,,,,,
LUIS,Yolanda Olivia Piña Maciel,Ginecología y Obstetricia,Biología de la Reproducción,San Ángel Inn ACORA,,,,,,,,,,,,,
LUIS,Yolitsma Arlet Muciño Manjarrez,Ginecología y Obstetricia,,HMG,,,,,,,,,,,,,
LUIS,Yunuen García Cortés,Ginecología y Obstetricia,,San Ángel Inn ACORA,,,,,,,,,,,,,
TALINA,Zaniru Raúl Marín Martínez,Ginecología Oncológica,Ginecología y Obstetricia,Hospital Ángeles Acoxpa,,,,,,,,,,,,,`;

export const parseData = (): Doctor[] => {
  const lines = RAW_DATA.trim().split('\n');
  // Skip header if it exists
  const startIndex = lines[0].startsWith('EJECUTIVO') ? 1 : 0;
  const doctors: Doctor[] = [];

  for (let i = startIndex; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim()) continue;

    // Split by comma
    const parts = line.split(',');
    
    const executive = (parts[0]?.trim() || 'SIN ASIGNAR').toUpperCase();
    const name = (parts[1]?.trim() || 'DESCONOCIDO').toUpperCase();
    const specialty = (parts[2]?.trim() || 'Ginecología y Obstetricia').toUpperCase();
    const subSpecialty = (parts[3]?.trim() || '').toUpperCase();
    const address = (parts[4]?.trim() || '').toUpperCase();
    const hospital = (parts[5]?.trim() || '').toUpperCase();
    const officeNumber = parts[6]?.trim();
    const floor = parts[7]?.trim();
    const phone = parts[8]?.trim();
    const email = parts[9]?.trim();
    const cedula = parts[10]?.trim();
    const birthDate = parts[11]?.trim();

    if (name && name !== 'DESCONOCIDO') {
        const initialSchedule: ScheduleSlot[] = [
            { day: 'LUNES', time: '', active: false },
            { day: 'MARTES', time: '', active: false },
            { day: 'MIÉRCOLES', time: '', active: false },
            { day: 'JUEVES', time: '', active: false },
            { day: 'VIERNES', time: '', active: false },
            { day: 'SÁBADO', time: '', active: false },
            { day: 'TODOS LOS DÍAS', time: '', active: false }
        ];

        doctors.push({
          id: `doc-${i}`,
          category: 'MEDICO',
          executive,
          name,
          specialty,
          subSpecialty,
          address,
          hospital,
          officeNumber,
          floor,
          phone,
          email,
          cedula,
          birthDate,
          visits: [],
          isInsuranceDoctor: false, 
          schedule: initialSchedule
        });
    }
  }

  // Common Hospitals
  const hospitalsToAdd = [
      { executive: 'ANGEL', name: 'HOSPITAL DALINDE' },
      { executive: 'ANGEL', name: 'ANGELES ROMA' },
      { executive: 'LUIS', name: 'ANGELES UNIVERSIDAD', address: 'AV. UNIVERSIDAD 1080' },
      { executive: 'LUIS', name: 'SAN ANGEL INN ACORA' },
      { executive: 'ORALIA', name: 'ANGELES LINDAVISTA' },
      { executive: 'TALINA', name: 'ANGELES PEDREGAL' },
      { executive: 'TALINA', name: 'MEDICA SUR' },
  ];

  hospitalsToAdd.forEach((hosp, idx) => {
      const initialSchedule: ScheduleSlot[] = [
          { day: 'LUNES', time: '', active: false },
          { day: 'MARTES', time: '', active: false },
          { day: 'MIÉRCOLES', time: '', active: false },
          { day: 'JUEVES', time: '', active: false },
          { day: 'VIERNES', time: '', active: false },
          { day: 'SÁBADO', time: '', active: false },
          { day: 'TODOS LOS DÍAS', time: '', active: false }
      ];
      
      doctors.push({
          id: `hosp-${idx}-${Date.now()}`,
          category: 'HOSPITAL',
          executive: hosp.executive,
          name: hosp.name,
          specialty: 'HOSPITAL',
          address: hosp.address || '',
          visits: [],
          isInsuranceDoctor: false,
          schedule: initialSchedule
      });
  });

  return doctors;
};